kind: Deployment
apiVersion: apps/v1
metadata:
  name: psb-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psb-fe
  template:
    metadata:
      labels:
        app: psb-fe
    spec:
      containers:
      - name: psb-fe
        image: leqvin/psb-fe:amd64
        imagePullPolicy: Always
        ports:
        - containerPort: 80
